[2023-10-25T12:05:34.962+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.inaccurate scheduled__2023-09-10T00:00:00+00:00 [queued]>
[2023-10-25T12:05:34.968+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.inaccurate scheduled__2023-09-10T00:00:00+00:00 [queued]>
[2023-10-25T12:05:34.968+0530] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-25T12:05:34.977+0530] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): inaccurate> on 2023-09-10 00:00:00+00:00
[2023-10-25T12:05:34.981+0530] {standard_task_runner.py:57} INFO - Started process 54771 to run task
[2023-10-25T12:05:34.983+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'first_dag', 'inaccurate', 'scheduled__2023-09-10T00:00:00+00:00', '--job-id', '1385', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpo7sgc2_m']
[2023-10-25T12:05:34.984+0530] {standard_task_runner.py:85} INFO - Job 1385: Subtask inaccurate
[2023-10-25T12:05:35.005+0530] {task_command.py:415} INFO - Running <TaskInstance: first_dag.inaccurate scheduled__2023-09-10T00:00:00+00:00 [running]> on host harika-Latitude-5511
[2023-10-25T12:05:35.048+0530] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2023-09-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-10T00:00:00+00:00'
[2023-10-25T12:05:35.049+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-25T12:05:35.049+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2023-10-25T12:05:35.056+0530] {subprocess.py:86} INFO - Output:
[2023-10-25T12:05:35.057+0530] {subprocess.py:93} INFO - inaccurate
[2023-10-25T12:05:35.057+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2023-10-25T12:05:35.067+0530] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=inaccurate, execution_date=20230910T000000, start_date=20231025T063534, end_date=20231025T063535
[2023-10-25T12:05:35.114+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-25T12:05:35.125+0530] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
