[2023-11-06T16:37:42.699+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hooks_demo.transfer manual__2023-11-06T11:02:35.762272+00:00 [queued]>
[2023-11-06T16:37:42.703+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hooks_demo.transfer manual__2023-11-06T11:02:35.762272+00:00 [queued]>
[2023-11-06T16:37:42.703+0530] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2023-11-06T16:37:42.712+0530] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transfer> on 2023-11-06 11:02:35.762272+00:00
[2023-11-06T16:37:42.715+0530] {standard_task_runner.py:57} INFO - Started process 51131 to run task
[2023-11-06T16:37:42.717+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'hooks_demo', 'transfer', 'manual__2023-11-06T11:02:35.762272+00:00', '--job-id', '4348', '--raw', '--subdir', 'DAGS_FOLDER/hooks.py', '--cfg-path', '/tmp/tmp8mgkvsbb']
[2023-11-06T16:37:42.718+0530] {standard_task_runner.py:85} INFO - Job 4348: Subtask transfer
[2023-11-06T16:37:42.739+0530] {task_command.py:415} INFO - Running <TaskInstance: hooks_demo.transfer manual__2023-11-06T11:02:35.762272+00:00 [running]> on host harika-Latitude-5511
[2023-11-06T16:37:42.875+0530] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='hooks_demo' AIRFLOW_CTX_TASK_ID='transfer' AIRFLOW_CTX_EXECUTION_DATE='2023-11-06T11:02:35.762272+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-06T11:02:35.762272+00:00'
[2023-11-06T16:37:42.880+0530] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-11-06T16:37:42.893+0530] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-11-06T16:37:42.902+0530] {logging_mixin.py:151} INFO - records [('Los Angles                                        ', 'ls                  '), ('Houston                                           ', 'ht                  ')]
[2023-11-06T16:37:42.904+0530] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/harika/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/harika/airflow/dags/hooks.py", line 35, in transfer_function
    execute_values(destination_cursor, "insert into target_city_table values %s", records)
  File "/home/harika/.local/lib/python3.10/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.InvalidTextRepresentation: malformed array literal: "Los Angles                                        "
LINE 1: insert into target_city_table values ('Los Angles           ...
                                              ^
DETAIL:  Array value must start with "{" or dimension information.

[2023-11-06T16:37:42.906+0530] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=hooks_demo, task_id=transfer, execution_date=20231106T110235, start_date=20231106T110742, end_date=20231106T110742
[2023-11-06T16:37:42.919+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 4348 for task transfer (malformed array literal: "Los Angles                                        "
LINE 1: insert into target_city_table values ('Los Angles           ...
                                              ^
DETAIL:  Array value must start with "{" or dimension information.
; 51131)
[2023-11-06T16:37:42.969+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-06T16:37:42.980+0530] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
