[2023-10-26T10:19:44.726+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.inaccurate scheduled__2023-10-25T00:00:00+00:00 [queued]>
[2023-10-26T10:19:44.735+0530] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.inaccurate scheduled__2023-10-25T00:00:00+00:00 [queued]>
[2023-10-26T10:19:44.735+0530] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-26T10:19:44.746+0530] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): inaccurate> on 2023-10-25 00:00:00+00:00
[2023-10-26T10:19:44.749+0530] {standard_task_runner.py:57} INFO - Started process 9312 to run task
[2023-10-26T10:19:44.751+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'first_dag', 'inaccurate', 'scheduled__2023-10-25T00:00:00+00:00', '--job-id', '1664', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpwn5mibw2']
[2023-10-26T10:19:44.753+0530] {standard_task_runner.py:85} INFO - Job 1664: Subtask inaccurate
[2023-10-26T10:19:44.779+0530] {task_command.py:415} INFO - Running <TaskInstance: first_dag.inaccurate scheduled__2023-10-25T00:00:00+00:00 [running]> on host harika-Latitude-5511
[2023-10-26T10:19:44.837+0530] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2023-10-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-25T00:00:00+00:00'
[2023-10-26T10:19:44.838+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-26T10:19:44.839+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2023-10-26T10:19:44.849+0530] {subprocess.py:86} INFO - Output:
[2023-10-26T10:19:44.850+0530] {subprocess.py:93} INFO - inaccurate
[2023-10-26T10:19:44.850+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2023-10-26T10:19:44.867+0530] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=inaccurate, execution_date=20231025T000000, start_date=20231026T044944, end_date=20231026T044944
[2023-10-26T10:19:44.883+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-26T10:19:44.894+0530] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
